---

- hosts: all
  become: true
  become_user: root
  
  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: Include extra variables
      include_vars:
        file: "{{ ansible_env.EXTRA_VAR_FILE }}"
      when: 
        - ansible_env['EXTRA_VAR_FILE'] is defined

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

  post_tasks:
    - name: Fetch admin.conf to local machine
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconf/{{ ansible_nodename }}_admin.conf
        flat: yes
        fail_on_missing: no
      when:
        - kubernetes_role == 'master'

    # workaround for dashboard
    - include_tasks: tasks/install_dashboard.yml
      when:
        - kubernetes_role == 'master'

    - include_tasks: tasks/grant_dashboard_token.yml
      when:
        - kubernetes_role == 'master'
